name: PulveSys App CI/CD
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: self-hosted
    env:
      NEXT_PUBLIC_API_URL: ${{secrets.NEXT_PUBLIC_API_URL}}
    strategy:
      matrix:
        node-version: [22.x]
    steps:
    - uses: actions/checkout@v4
    - name: Setup pnpm
      uses: pnpm/action-setup@v4.1.0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm i
    - name: Build app
      run: pnpm run build --if-present
  run:
    runs-on: self-hosted
    steps:
    - name: Reload proxy server
      run: pm2 reload pulvesys-app --update-env
