name: PulveSys Beta App CI/CD
on:
  push:
    branches: ['develop']
defaults:
  run:
    working-directory: ./develop
jobs:
  build_run:
    runs-on: self-hosted
    env:
      NEXT_PUBLIC_API_URL: ${{secrets.NEXT_PUBLIC_DEVELOPMENT_API_URL}}
      NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN: ${{secrets.NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN}}
      NEXT_PUBLIC_MAX_EMPLOYERS: ${{secrets.NEXT_PUBLIC_MAX_EXPLOYERS}}
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v4
        with:
          path: develop
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 10
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: ./develop
      - name: Install dependencies
        run: pnpm i
        working-directory: ./develop
      - name: Build beta app
        run: pnpm run build
        working-directory: ./develop
      - name: Reload beta proxy server
        run: pm2 reload beta.pulvesys.com --update-env
